### ISSUE TITLE
Javascript workers on external-task-pattern-with-js-workers reference a non local dependency

### ISSUE THREAD

**Issue by ccristian** [camunda-consulting/code#38]
"dependencies": {
    "camunda-worker-node": "file:..",
    "uuid": "^2.0.1"
  }

should be 

  "dependencies": {
    "camunda-worker-node": "https://github.com/nikku/camunda-worker-node",
    "uuid": "^2.0.1"
  }

for the https://github.com/camunda-consulting/code/tree/master/snippets/external-task-pattern-with-js-workers

**Comment by falko** [comment]
@NPDeehan since you added the snippet, could you take care of that.

**Comment by NPDeehan** [comment]
That change has been made.

**Comment by ccristian** [comment]
if you run nmp install as it is it will fail as you do not have locally the workers
to work please add "camunda-worker-node": "https://github.com/nikku/camunda-worker-node",
not "camunda-worker-node": "file:..",
