### ISSUE TITLE
Can we have a working example of integrating Azure AD with springboot-security-sso

### ISSUE THREAD

**Issue by prasenjithaty** [camunda-consulting/code#43]
I'm trying to figure out how to integrate Azure AD with "springboot-security-sso". Can we have a document or a working example?

**Comment by benhoffmann** [comment]
Hi @prasenjithaty 

If you are only looking for using Azure AD as an Identity Provider, check out [Camunda's LDAP plugin](https://docs.camunda.org/manual/7.8/user-guide/process-engine/identity-service/#the-ldap-identity-service )

For real SSO, you'll also need to integrate with some suitable authentication mechanism like Kerberos or OAuth.

Please note that we usually do not use GitHub issues for this repo. If you have any more questions, please use the [official Camunda forum](https://forum.camunda.org) to ensure you get fast replies.

**Comment by Muhammadinaam** [comment]
Please check this: https://github.com/finexioinc/camunda-azure-sso-boilerplate
