### ISSUE TITLE
SSO and saving users in Camunda DB.

### ISSUE THREAD

**Issue by romankh3** [camunda-consulting/code#47]
Hello! Related to [Spring Security Camunda](https://github.com/camunda-consulting/code/tree/master/snippets/springboot-security-sso)
I have a question about SSO. In regards for the case when SSO is working, but for this case, users don't save into Camunda database. After authentication logs show us warning about it.

It's good to save the data into the User database.
How do you think, how can it be implemented?

**Comment by falko** [comment]
With SSO you can either use the LDAP plugin to load the groups of an authenticated user or provide them as part of the SSO.

**Comment by falko** [comment]
Duplicating user data into Camunda's database is not recommended if another system is managing them.

**Comment by romankh3** [comment]
I got it. Thanks for an answer.
