### ISSUE TITLE
i can't run the camunda-vue-app project

### ISSUE THREAD

**Issue by kamaleshsivaraj** [camunda-consulting/code#50]
![image](https://user-images.githubusercontent.com/38140254/50504558-66f0b780-0a94-11e9-86da-b0222c610901.png)
i try to run the project but an error as been established ,so can any one solve this.

**Comment by mathiasconradt** [comment]
Which node Version are you using? Maybe try an older one using "nvm use", just a thought...  Haven't tried myself

**Comment by kamaleshsivaraj** [comment]
my node version 10.8.0 @mathiasconradt

**Comment by falko** [comment]
The repo is actually more than five years old, but since it is a collection of examples and recipes that doesn't tell you much about the node version. The Vue.js example is just about a year old.

**Comment by falko** [comment]
There is a `yarn.lock` file in the repo. So it was probably built with `yarn` originally. Could you try that?

**Comment by falko** [comment]
I tried it myself and couldn't get it to run with neither `npm` nor `yarn`. @felix-mueller any ideas?

**Comment by kamaleshsivaraj** [comment]
i just tried whether it will work in latest version of npm or not.Well,thanks for the post you saved my day.@mathiasconradt

**Comment by kamaleshsivaraj** [comment]
the same doubt i raised with this issues @falko

**Comment by falko** [comment]
@kamaleshsivaraj how did you solve it in the end?

**Comment by kamaleshsivaraj** [comment]
No @falko i didn't solved. The same issue has been continuing.Like @mathiasconradt said i want to go back for 2years and i wanna to check .and @falko did u check this issue if you solved let me know !?

**Comment by kamaleshsivaraj** [comment]
I have tried all the method were suggested by everyone till the date i can't solve the issue shows same error message. the only thing to solve this the created author @felix-mueller wants to make some changes.
i request @felix-mueller  to rebuild same camunda-vue-app project with latest version of vue-cli,nodejs.
and also  i tried camunda-angular-app some error established because of  some dependencies not working properly because the angular cli 1.6.7 has been not in maintenance also rebuild it @felix-mueller .finally i tried camunda-react-app its work fine with yarn and without no error. i didn't tried with npm.!

**Comment by felix-mueller** [comment]
Thanks for the info @kamaleshsivaraj 
I reopened the issue, so I can investigate the error and eventually upgrade to the latest CLIs
I dont know yet when this will happen so, but I will let you know

**Comment by felix-mueller** [comment]
Hey @kamaleshsivaraj 
I updated the project to the latest vue version and made it work with the latest yarn version:

yarn --version: 1.12.3
vue --version: 3.2.3
node --version: v10.5.0

**Comment by felix-mueller** [comment]
@kamaleshsivaraj thanks for your feedback. I am not sure I understand your doubt - if this is unrelated to this issue, then I believe it might make sense to post a message in our forum https://forum.camunda.org/

**Comment by felix-mueller** [comment]
I will close this ticket for now
