### ISSUE TITLE
ReadMe of Customize the Camunda Webapps in Spring Boot

### ISSUE THREAD

**Issue by yanavasileva** [camunda-consulting/code#53]
Hello,

The ReadMe file of https://github.com/camunda-consulting/code/tree/master/snippets/springboot-customized-webapps is not updated after 7.10 changes with the correct path:

> Possibly addionally adjust the contents of `springboot-customized-webapp-webjar/src/main/resources/META-INF/resources/app/{tasklist|cockpit|admin}/{styles|scripts}/`

must be
`springboot-customized-webapp-webjar/src/main/resources/META-INF/resources/webjars/camunda/app/{tasklist|cockpit|admin}/{styles|scripts}/`

Best regards,
Yana

**Comment by falko** [comment]
@nevries could you take a look at this?

**Comment by ingorichtsmeier** [comment]
Done with https://github.com/camunda-consulting/code/commit/6cb7ee5524b5605007cbd940bb299da11c18ee81

**Comment by yanavasileva** [comment]
👍
