### ISSUE TITLE
Documentation link on the README page is broken

### ISSUE THREAD

**Issue by sleyzerzon** [camunda-consulting/code#71]
The Documentation link at the very bottom gives 404.

**Comment by falko** [comment]
Which link on which README file?

**Comment by sleyzerzon** [comment]
[This](https://github.com/camunda-consulting/code/tree/master/snippets/camunda-modeler-plugins/camunda-modeler-plugin-usertask-generatedform-preview) page, down below, in the **Installation** section.

**Comment by falko** [comment]
I think you're right. Would you like to create a pull request? You can just edit the file using the GitHub website.

**Comment by sleyzerzon** [comment]
https://github.com/camunda-consulting/code/pull/72

**Comment by falko** [comment]
Closed by PR #72 

Thank you!
