### ISSUE TITLE
SpringBoot Customized WebApp Welcome Page

### ISSUE THREAD

**Issue by yangricardo** [camunda-consulting/code#79]
Hi, i tried to copy the code from cockpit, admin and tasklist examples, doing some updates to customize the welcome page, and it`s loading forever... i can access the other applications well, but would be interesting to update this repository to show the example to the welcome page

**Comment by falko** [comment]
Any errors in the javascript console?

**Comment by yangricardo** [comment]
At the day, i think i was just using the wrong statements, like:
Admin: window.camAdminConf {...}
Tasklist: window.camTasklistConf {...}
Cockpit: window.camCockpitConf {...}
Welcome: window.camWelcomeConf {...}
